import '../css/style.css';

function Footer() {
  return (
    <footer className="footer-theme p-4">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-center gap-1 sm:gap-2">
        <span className="font-bold font-patrick text-sm sm:text-base text-center sm:text-left">
          &copy; 2025 Vispiv Collectives
        </span>
        
        {/* Hide pipe on mobile, show on sm+ */}
        <span className="hidden sm:inline font-patrick text-sm sm:text-base">|</span>
        
        <span className="font-bold font-patrick text-sm sm:text-base text-center sm:text-left">
          Images generated by Nano Banana 🍌 using Gemini AI
        </span>
      </div>
    </footer>
  );
}

export default Footer;